/* eslint-disable unicorn/prevent-abbreviations */
// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.svg?raw" {
  /**
   * The raw SVG content as a string
   */
  const content: string;
  export = content;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
