name: Bug Report on code
description: Describe your bug with Mousehole

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Only file bugs here!

  - type: textarea
    id: reproducer
    attributes:
      label: I did this
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: I expected the following
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: I got this instead
    validations:
      required: true

  - type: textarea
    id: server-logs
    attributes:
      label: Server logs
      description: |
        Please post your server logs. Copy-paste, or, on docker, you can run 
        `docker logs mousehole > mousehole-logs.txt` to save the logs to a file.
    validations:
      required: true

  - type: textarea
    id: compose-file
    attributes:
      label: Compose file
      description: |
        Please post your entire compose file if you are using one, redacting any
        sensitive information or N/A if not using a compose file.
    validations:
      required: true
