blank_issues_enabled: false
contact_links:
  - name: Need help?
    url: https://github.com/t-mart/mousehole/discussions/new?category=q-a
    about: Ask support questions in Discussions, not Issues.
  - name: Feature request
    url: https://github.com/t-mart/mousehole/discussions/new?category=ideas
    about: Suggest new features in Discussions, not Issues.
