name: Bug Report on documentation
description: Problems, errors, mistakes or typos in documentation.
labels: documentation

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Only file documentation bugs here!

  - type: textarea
    id: source
    attributes:
      label: Specify which documentation you found a problem with
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: The problem
    validations:
      required: true